apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphai
  labels:
    app.kubernetes.io/name: graphai
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8010
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: graphai
